### ISSUE TITLE
cannot importnameMeCab'from partially initialized module 'MeCab'

### ISSUE THREAD

**Issue by hakusetsu1995** [SamuraiT/mecab-python3#102]
I installed MeCab through

mecab_python3-1.0.9-cp312-cp312-win32.whl 

and got this error
```
>>> import MeCab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\my python\Lib\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: cannot import name ' **_MeCab**'  from partially initialized module 'MeCab' (most likely due to a circular import) (D:\my python\Lib\site-packages\MeCab\__init__.py)
```
How can I fix it?

python3.12.3(32bit)
Windows11

**Comment by polm** [comment]
Circular imports are usually caused by having a file named `mecab.py` in your current working directory. Do you have a file like that? Also, to be clear, are you using the REPL, or are you running code from a file?

**Comment by hakusetsu1995** [comment]
Thank you for your reply.
There is no file named` mecab.py` I installed MeCab through `mecab_python3-1.0.9-cp312-cp312-win32.whl `,and I'm using IDLE to run import MaCab.

**Comment by polm** [comment]
Hm, I'm not really sure what the cause would be then. I checked my records and I've never seen this issue except due to problems with source files with the same name. Here are some things to check:

- how did you install Python? Was it through the Windows Store, Python.org, or another way?
- how did you install the wheel file? Did you run `pip install mecab-python3`?
- If you put simple code in a file in an empty directory can you run it?
- What directory are you running IDLE from?

Example simple code:

```
import MeCab

tagger = MeCab.Tagger()
print(tagger.parse("pythonが大好きです"))
```

**Comment by polm** [comment]
Closing due to lack of response, but feel free to follow up if you can provide more details.
