### ISSUE TITLE
Causing whisper hallucinations. 

### ISSUE THREAD

**Issue by sin2piusc** [SamuraiT/mecab-python3#103]
Does not have a negative effect on WER or CER eval metrics (hugging face) but causes whisper hallucinations in practice. Transcription + translation to English with whisper small medium large v2 and v3 fine-tuned with cleaned/processed common voice + fleurs + jsut. Might have something todo with character spacing/grouping. Possibly not an issue with the wrapper but rather how mecab interacts with whisper.

**Comment by polm** [comment]
I understand you have an issue when using MeCab in combination with the Whisper speech recognition model, but from the above description it's not clear how you're using MeCab or why it would cause the issue. It sounds like you should report this at the Whisper repo and not here until you have a detailed example of the problem and how MeCab causes it. 

Closing because there is no action to be taken.
