### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 15: invalid start byte

### ISSUE THREAD

**Issue by JNULYD** [SamuraiT/mecab-python3#27]
My python version is python 3.6.5
When i try to install mecab-python3, Exception appear like this

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 15: invalid start byte

**Comment by zackw** [comment]
I need more information in order to investigate this problem:

* What operating system are you using?
* Are you installing into a virtualenv, a user context, or systemwide?
* Please tell me the exact sequence of commands you gave in order to install mecab-python3.
* Please show the _complete and unedited_ output of the `printenv` command in the environment where you tried to install mecab-python3.

**Comment by zackw** [comment]
Also, we are preparing a new release that has fixed many bugs.  If you have time, please try the new wheels from https://test.pypi.org/project/mecab-python3/0.996.2rc2/ .

**Comment by JNULYD** [comment]
Operating system is Windows 8.1 profession. And i wanted to install mecab-python3 using virtualenv environment.
After many attempts, it could not work anyway, and i gived up, then used another package -- "mecab-python-windows", and it worked! Thanks to this package, it make my job work!

Thanks your response and help any way!

**Comment by zackw** [comment]
Oh. Indeed, this package is not prepared to work on Windows yet. I'm surprised this manifested as a UnicodeDecodeError when running `setup.py` but that's probably not important right now.

Thank you for telling me about mecab-python-windows, I may be able to reuse some of their tooling.
