### ISSUE TITLE
Returns only top result with NBest option

### ISSUE THREAD

**Issue by itmammoth** [SamuraiT/mecab-python3#36]
Hi,
I am trying to parse some words with the `NBest` option, but it doesn't seem to work correctly.

* mecab 0.996
* mecab-ptyhon3 0.996.2
* python 3.7.4

What mecab returns is

```shell
$ echo こんにゃく粉 | mecab -N2
こんにゃく粉	名詞,一般,*,*,*,*,こんにゃく粉,コンニャクコ,コンニャクコ
EOS
こんにゃく	名詞,一般,*,*,*,*,こんにゃく,コンニャク,コンニャク
粉	名詞,接尾,一般,*,*,*,粉,コ,コ
EOS
```

On the other hand, what mecab-python3 returns is

```python
import MeCab

tagger = MeCab.Tagger('-N2')
print(tagger.parse('こんにゃく粉'))
```
```
こんにゃく粉     名詞,一般,*,*,*,*,こんにゃく粉,コンニャクコ,コンニャクコ
EOS
```

**Comment by polm** [comment]
The `-N` option doesn't work that way when initializing the tagger, you need to use an nbest related method in the API. Example:

    tagger.parseNBest(2, 'こんにゃく粉')
    # =>  'こんにゃく 粉 \nこんにゃく 粉 \n'
    # note: I get the same results for the top two, probably because I'm using Unidic.

In general, be careful because the command line works slightly differently from the C API in MeCab. Another example is that from the command line all newlines are treated as sentence boundaries, while from the API they're just whitespace.

**Comment by itmammoth** [comment]
Thanks @polm !
You saved my day.
