### ISSUE TITLE
Failed when trying to initialize MeCab. Some things to check:

### ISSUE THREAD

**Issue by loretoparisi** [SamuraiT/mecab-python3#51]
I'm getting this error since latest update.

```

Failed when trying to initialize MeCab. Some things to check:

    - If you are not using a wheel, do you have mecab installed?

    - Do you have a dictionary installed? If not do this:

        pip install unidic-lite

    - If on Windows make sure you have this installed:

        https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

    - Try creating a Model with the same arguments as your Tagger; that may
      give a more descriptive error message.

If you are still having trouble, please file an issue here:

    https://github.com/SamuraiT/mecab-python3/issues
```

**Comment by polm** [comment]
Can you install the latest version (1.0.1) and paste the error output from that?

**Comment by loretoparisi** [comment]
@polm okay we will try to update to the latest version and check the error again.

**Comment by greenfalcon** [comment]
Hello. I'm MeCab beginner.
I am also getting error when trying to initialize MeCab.
When I downloaded latest version, the file size was only 3.5MB as follows. (former version was 17MB) 
I thought it might be the cause of this error. 
May I have your comment on this ?
-------------------------------------------------------
Collecting mecab-python3
  Downloading https://files.pythonhosted.org/packages/8b/06/2aeff86243c88580ccf78b136d403ce5e0a1eed9091103157f01e806499f/mecab_python3-1.0.1-cp36-cp36m-manylinux2010_x86_64.whl (3.5MB)
     |████████████████████████████████| 3.5MB 2.8MB/s 
Installing collected packages: mecab-python3
Successfully installed mecab-python3-1.0.1

**Comment by polm** [comment]
Hello greenfalcon.

The output you posted doesn't have an error. Are you getting an error? If so, could you paste it here?

What version did you have before? If it was 17MB, you probably had a version that included ipadic. The newest version doesn't include ipadic, you need to install a dictionary separately.

**Comment by greenfalcon** [comment]
Thank you for your reply. The file which I downloaded before is mecab-0.996. 
I got following error.

[From here]
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: mecab-ipadic-neologd
error message: [ifs] no such file or directory: /usr/local/etc/mecabrc
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-3d35f7aa84ce> in <module>()
      4   #改行で切り分けて各行ごとに形態素解析を行います。
      5   for i in text_list.split('\n'):
----> 6     mecab = MeCab.Tagger('mecab-ipadic-neologd').parse(i)
      7     #用意したm_listに格納します。
      8     m_list.append(mecab)

/usr/local/lib/python3.6/dist-packages/MeCab/__init__.py in __init__(self, rawargs)
    122 
    123         try:
--> 124             super(Tagger, self).__init__(args)
    125         except RuntimeError:
    126             error_info(rawargs)

RuntimeError: 


And then, following texts are part of the messages when I installed MeCab.

[Before]
Collecting mecab-python3
  Downloading https://files.pythonhosted.org/packages/8b/06/2aeff86243c88580ccf78b136d403ce5e0a1eed9091103157f01e806499f/mecab_python3-1.0.1-cp36-cp36m-manylinux2010_x86_64.whl (3.5MB)
     |████████████████████████████████| 3.5MB 2.8MB/s 
Installing collected packages: mecab-python3
Successfully installed mecab-python3-1.0.1

[This time]
Collecting mecab-python3
  Downloading https://files.pythonhosted.org/packages/18/49/b55a839a77189042960bf96490640c44816073f917d489acbc5d79fa5cc3/mecab_python3-0.996.5-cp36-cp36m-manylinux2010_x86_64.whl (17.1MB)
     |████████████████████████████████| 17.1MB 242kB/s 
Installing collected packages: mecab-python3
Successfully installed mecab-python3-0.996.5

**Comment by polm** [comment]
This is your error:

> error message: [ifs] no such file or directory: /usr/local/etc/mecabrc

This is how you are creating MeCab:

> mecab = MeCab.Tagger('mecab-ipadic-neologd').parse(i)

That is not correct. You need to find out where neologd is installed. Then you can do something like this:

> # /home/hoge/neologd is the path where neologd is installed
> mecab = MeCab.Tagger('-d /home/hoge/neologd') 

But you also need to specify a mecabrc file, like the error says. If you do not know where your mecabrc file is, you can do this:

> mecab = MeCab.Tagger('-r /dev/null -d /home/hoge/neologd')

Then it should work.

Also, if you are just getting started with MeCab, you shouldn't use neologd. It makes everything more complicated. After you get used to MeCab you can start using neologd if it's right for your task. If you can do without neologd, then if you do this the new version should just work:

    pip install unidic-lite

**Comment by loretoparisi** [comment]
@polm just adding that before version `1.0.1` we did not experience this issue.
My code (not changed before and after the issue) is the following:

```python
import MeCab
# Mecab tokenizer for Japanese
MECAB = os.path.join(TOOL_BASE_DIR, 'mecab')

#....

if lang == 'zh':
        # jieba -d
        seg_list = jieba.cut(tok, cut_all=False)
        tok = " ".join(seg_list)
    elif lang == 'ja':
        # mecab -O wakati -b 50000
        mecab = MeCab.Tagger("-Owakati -b 5000")
        tok = mecab.parse(tok)

```

**Comment by polm** [comment]
@loretoparisi What is your actual error output with `1.0.1`?

**Comment by polm** [comment]
@loretoparisi Did you figure this out? Let me know if there's anything I can help with, though I need to see the error output to be able to understand what's going on.

**Comment by loretoparisi** [comment]
> @loretoparisi Did you figure this out? Let me know if there's anything I can help with, though I need to see the error output to be able to understand what's going on.

Please wait I'm building the container and checking...

**Comment by loretoparisi** [comment]
@polm I updated the code to `1.0.1`. This is the error I get

```
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: -Owakati -b 5000
error message: [ifs] no such file or directory: /usr/local/etc/mecabrc
----------------------------------------------------------
```

**Comment by polm** [comment]
OK, thanks, that makes the issue clear - mecab can't find your mecabrc. You can fix that issue by adding `-r /path/to/mecabrc` to the `Tagger` args. 

Also, as a separate comment - I don't think your `MECAB` and `TOOL_BASE_DIR` variables do anything. 0.966.1 or higher (anything released from the end of 2018 to now) comes with wheels, so you're using a bundled mecab binary instead of the system mecab binary unless you're specifically building the package from source. The package also doesn't read special variables like that and you're not passing it anything... In your case, assuming you have no important settings in the system mecab, you can just not install it.

**Comment by loretoparisi** [comment]
@polm thank you. You say that I do not need anymore the `mecab` binary since it's bundled with this package then?

**Comment by loretoparisi** [comment]
**[UPDATE]**
so it seems if finds both the dictionary with `-d` and the config file with `-r`, but I now get the error
```
'utf-8' codec can't encode characters in position 4-5: surrogates not allowed
```

My input sentence was `"こんにちは、元気ですか"`

while the IPADict config is

```
;
; Configuration file of IPADIC
;
; $Id: dicrc,v 1.4 2006/04/08 06:41:36 taku-ku Exp $;
;
cost-factor = 800
bos-feature = BOS/EOS,*,*,*,*,*,*,*,*
eval-size = 8
unk-eval-size = 4
config-charset = EUC-JP

; yomi
node-format-yomi = %pS%f[7]
unk-format-yomi = %M
eos-format-yomi  = \n

; simple
node-format-simple = %m\t%F-[0,1,2,3]\n
eos-format-simple  = EOS\n

; ChaSen
node-format-chasen = %m\t%f[7]\t%f[6]\t%F-[0,1,2,3]\t%f[4]\t%f[5]\n
unk-format-chasen  = %m\t%m\t%m\t%F-[0,1,2,3]\t\t\n
eos-format-chasen  = EOS\n

; ChaSen (include spaces)
node-format-chasen2 = %M\t%f[7]\t%f[6]\t%F-[0,1,2,3]\t%f[4]\t%f[5]\n
unk-format-chasen2  = %M\t%m\t%m\t%F-[0,1,2,3]\t\t\n
eos-format-chasen2  = EOS\n
```

**Comment by polm** [comment]
> You say that I do not need anymore the mecab binary since it's bundled with this package then?

Yes, since version 0.966.1 (released late 2018) the package has always had Linux wheels. It's possible you're building from source and not using them, but you should know if you're doing that.

Note that the versions that included their own binary also bundled ipadic, so your system dictionary wasn't being used, but instead a bundled version of the same thing was.

> but I have just checked I'm actually not using that binary install anymore, so why is asking me to mecabrc file? Do I really need one?

MeCab requires a mecabrc to exist in order to run, and sometimes people put useful settings in there like user dictionaries. This library doesn't include a mecabrc because it should use your system one if it's there. However, it's very common for nothing to be in there except the dictionary path, so you can just use `-r /dev/null` and also specify the dictionary path with `-d` instead.

> 'utf-8' codec can't encode characters in position 4-5: surrogates not allowed

Ah OK, if you look at the dicrc you'll see it says the dictionary charset is euc-jp. Python tries to render that as utf-8 and fails. You have a couple of options:

- `pip install unidic-lite`. This will install the unidic dictionary, and should let your code work without the `-r` or `-d` args. However, while unidic is better than ipadic, it's also quite different, so you need to check the changes.
- Install a utf8 verion of ipadic from source or with a system package manager
- try an alpha version of ipadic I'm working on

I'm working on a pip-installable version of utf8 ipadic, you can try it by first using `pip install ipadic==1.0.0a2` and then instantiating MeCab like this:

    import ipadic
    tagger = MeCab.Tagger(ipadic.MECAB_ARGS + ' ' + your_mecab_args)

That should get an official release next week or so. However, for reasons I escribe in that projects [README](https://github.com/polm/ipadic-py), you should switch to Unidic if at all possible.

-----

Sorry for all the information - configuring MeCab is unfortunately complicated. My intent with the latest version is that installing `mecab-python3` and `unidic-lite` just works, but it can complicated for existing installs that were unaware of how the bundling worked.

**Comment by polm** [comment]
I assume this is resolved, let me know if not. 

Also note that if you want to keep the same dictionary as before, ipadic is released on PyPI now. 

https://pypi.org/project/ipadic/

**Comment by madtunebk** [comment]
simple workaround the issue : **error message: [ifs] no such file or directory: /usr/local/etc/mecabrc,** it to download NPL dictionary  by : **python -m unidic download**

**Comment by polm** [comment]
@madtunebk That is [specifically called out in the README](https://github.com/SamuraiT/mecab-python3?tab=readme-ov-file#specifying-a-mecabrc) in the section linked from error messages. 

I'm locking this thread since it's three years old and there's no reason to follow up on it.
