### ISSUE TITLE
documentation of the parsed results?

### ISSUE THREAD

**Issue by YameiW** [SamuraiT/mecab-python3#91]
Hello there,

I am using Mecab to parse Japanese sentences. But I am confused by the results. Do you have some documents that I can read to understand the parsing results?

For instance, What does each column mean, and what is the meaning of some numbers in the last column? Does Mecab give us the dependency information that we can use to extract nominal phrases?

Any help would be appreciated!

<img width="723" alt="Screenshot 2023-02-28 at 1 09 29 PM" src="https://user-images.githubusercontent.com/49138382/221942444-8f26d7d4-3c28-4cad-8497-a9044a30c2cc.png">

**Comment by polm** [comment]
The output format depends on your config file and your dictionary. 

You seem to be using the full sized UniDic with accent information (the last column in your output), so you'll need to check your config file against the dictionary format. Or, instead, you could just use [fugashi](https://github.com/polm/fugashi), which will parse all UniDic fields into a namedtuple for easy use. See [here](https://github.com/polm/unidic-py) for an overview of fields.

MeCab cannot annotate the field names because they are not stored in the config or dictionary itself anywhere. 

Also MeCab does not generate any kind of dependency information. 

In general, [the official MeCab docs](https://taku910.github.io/mecab/) may be helpful.

**Comment by polm** [comment]
Closing this because I believe that answers your question, but if anything is unclear please feel free to follow up.
